// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmtOrderManager.Infrastructure.Persistence;

#nullable disable

namespace SmtOrderManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220163049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SmtOrderManager.Domain.Boards.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Boards.BoardComponent", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlacementQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("BoardComponents", (string)null);
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Components.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Orders.OrderBoard", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId", "BoardId");

                    b.HasIndex("BoardId");

                    b.ToTable("OrderBoards", (string)null);
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Boards.BoardComponent", b =>
                {
                    b.HasOne("SmtOrderManager.Domain.Boards.Board", null)
                        .WithMany("ComponentLinks")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmtOrderManager.Domain.Components.Component", null)
                        .WithMany("BoardLinks")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Orders.OrderBoard", b =>
                {
                    b.HasOne("SmtOrderManager.Domain.Boards.Board", null)
                        .WithMany("OrderLinks")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmtOrderManager.Domain.Orders.Order", null)
                        .WithMany("BoardLinks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Boards.Board", b =>
                {
                    b.Navigation("ComponentLinks");

                    b.Navigation("OrderLinks");
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Components.Component", b =>
                {
                    b.Navigation("BoardLinks");
                });

            modelBuilder.Entity("SmtOrderManager.Domain.Orders.Order", b =>
                {
                    b.Navigation("BoardLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
